buscar_dados_para_questao:
  description: |
    Com base no pedido do usuário {solicitacao_melhorada}, realize uma busca na internet
    para encontrar conteúdos que possam ser utilizados como texto-base em uma questão de vestibular.

    Use somente fontes em português.

    Use a ferramenta "Search the internet with Serper" usando o campo "search_query" com a pergunta ou tema principal

    Exemplo:
    {
      "search_query": "questões de vestibular sobre cinemática"
    } 
    **EXTRAÇÃO RAW**  
    - Use web.open para obter o HTML bruto.
    - Use web.find (ou equivalente) com `raw: true` para capturar **todos** os <p>…</p>.
    - **Copie e cole** cada parágrafo exatamente como está no HTML, incluindo acentos, quebras de linha e pontuação.
    - **Não** altere, resuma, parafraseie ou corrija o texto original.

    Depois disso, selecione um ou mais parágrafos (exatos) que possam ser utilizados como texto de apoio.
    Para cada um, explique por que ele é adequado para a elaboração de uma questão vestibular.

  steps:
    - tool: web.open
      args:
        url: "{{url}}"
    - tool: web.find
      args:
        ref_id: last
        pattern: "<p>.*?</p>"
      raw: true

  expected_output: >
    Um json sem ``` seguindo o exemplo abaixo
    {
      "fonte 1": {
        "url": "https://site1.com/exemplo",
        "texto_na_integra": "Aqui vai os parágrafos completos, exatamente como no site, sem nenhuma alteração.",
        "texto_apoio": "Aqui vai o parágrafo selecionado para servir de base.",
        "explicacao": "Este parágrafo aborda X, o que permite criar uma questão sobre Y em Biologia (Genética)."
      },
      "fonte 2": { … },
      "fonte 3": { … }
    }
  agent: pesquisa_e_extracao

geração_questao:
  description: >
    Gere uma questão inédita de múltipla escolha para simular um vestibular do Brasil seguindo o pedido do usuário:
    {solicitacao_melhorada}
    A questão deve ser elaborada no estilo dos principais exames brasileiros, focando na avaliação de competências essenciais do ensino médio.

    1. Estrutura da Questão:
      Enunciado: Deve ser autocontido, apresentando uma contextualização relevante e instigante (podendo ser um cenário 
      cotidiano, científico, histórico, social, etc.), seguida de uma pergunta principal clara e objetiva. O enunciado 
      deve ter entre 50 e 200 palavras.
      Alternativas: Crie 4 (quatro) alternativas de resposta, rotuladas como A, B, C, D.
    2. Qualidade das Alternativas:
      Correta: Apenas UMA alternativa deve ser inequivocamente correta, com base nos conhecimentos esperados para o 
      nível.
      Distratores: As outras três alternativas (distratores) devem ser plausíveis e atraentes, mas tecnicamente 
      incorretas. Idealmente, os distratores devem explorar erros conceituais comuns, interpretações parciais, 
      raciocínios falhos ou aplicação incorreta de fórmulas/conceitos. Evite alternativas absurdas ou facilmente 
      descartáveis.
    3. Conteúdo e Competências:
      A questão deve ser rigorosamente precisa em termos conceituais e factuais para o tópico fornecido.
      Deve avaliar habilidades cognitivas além da simples memorização, como interpretação de texto/dados, análise 
      crítica, raciocínio lógico, argumentação, resolução de problemas e aplicação de conhecimentos em novos contextos.
    4. Formato e Estilo:
      Utilize linguagem clara, precisa e adequada ao público do ensino médio e pré-vestibular.
      Se a questão envolver fórmulas matemáticas, gráficos, tabelas ou equações químicas, utilize a notação LaTeX 
      para representá-las corretamente. 
      A questão deve ser original, evitando cópias diretas de questões existentes, mas pode se inspirar na complexidade,
       no formato e no estilo de questões de exames anteriores.
    5. Restrições:
      Não inclua a identificação da resposta correta (gabarito) no texto do enunciado ou das alternativas. O gabarito 
      será especificado em um campo separado no JSON de saída.

      A questão deve ser solucionável com base no conhecimento tipicamente adquirido durante o Ensino Médio e utiizando
      raciocínio lógico.
    6. Não esquecer de colocar a URL da fonte de onde o texto de apoio foi retirado.
  
    {few_shot_prompt}
  expected_output: >
    Um objeto JSON contendo as chaves "texto_apoio", "enunciado" e "alternativas".
    A chave "texto_apoio" deve conter o trecho pesquisado pelo agente anterior.
    A chave "alternativas" deve ser um objeto com as chaves "A", "B", "C", "D", contendo os textos de cada alternativa.

    Exemplo de Saída:
    {
      "texto_apoio": "Durante o século XIX, a Revolução Industrial começou a substituir o trabalho artesanal e agrícola por processos de produção em fábricas. Pessoas que antes trabalhavam em pequenas propriedades rurais migraram em massa para centros urbanos em busca de emprego. Essa rápida urbanização fez com que bairros operários crescessem ao redor das indústrias, e as atividades diárias passaram a girar em torno do ritmo das máquinas e da disciplina fabril, ao invés dos ciclos sazonais do campo.",
      "Disponível em: http://thumbpress.com/. Acesso em: 28 out. 2013",
      "enunciado": "Considerando o contexto apresentado no texto de apoio, qual das seguintes alternativas representa uma consequência social significativa dessa transformação durante a Revolução Industrial?",
      "alternativas": {
        "A": "Reforço do trabalho em pequenas propriedades rurais, com retorno dos trabalhadores às vilas do interior.",
        "B": "Aumento da influência de monarquias agrárias que sustentavam sistemas feudais tradicionais.",
        "C": "Formação de uma nova classe operária urbana submetida a jornadas de trabalho extensas em fábricas.",
        "D": "Desenvolvimento de tecnologia de transportes que tornou obsoletos os navios a vapor."
      }
    }
  agent: redator_questao


resolucao_questao:
  description: >
    Solucione a questão de vestibular gerada previamente e explique o raciocínio por trás da resolução.
    Desenvolva a lógica de raciocínio e o embasamento teórico que fundamenta a resposta correta.
    Destaque a resposta final e alternativa correta entre as opções apresentadas. Se não houver uma alternativa correta, indique que a questão não possui uma resposta correta.
  expected_output: >
    Um json com as chaves "explicacao", "resposta_final" e "alternativa_correta" preenchidas com os valores correspondentes.

    Exemplo de saída:
    {
      "explicacao": "A velocidade média é dada pela fórmula V = d/t, onde d é a distância e t é o tempo. Neste caso, d = 100 km e t = 2 h. Portanto, V = 100 km / 2 h = 50 km/h.",
      "resposta_final": "50 km/h",
      "alternativa_correta": "A"
    }
  agent: resolutor_questao

correção_questao:
  description: >
    Analise criticamente e corrija exclusivamente o enunciado de uma questão de vestibular previamente gerada.
    Input: Você receberá uma questão completa (com "enunciado" original, "alternativas" e "gabarito").
    Sua Tarefa:

    1. Identifique e corrija erros de gramática (ortografia, concordância, regência, pontuação), imprecisões na 
    fundamentação teórica, ambiguidades, falta de clareza ou informações redundantes/ausentes no enunciado.
    2.  NÃO altere as "alternativas" nem o "gabarito" fornecidos. Seu trabalho é ajustar o enunciado para que ele 
    esteja correto, claro e totalmente alinhado com as alternativas e o gabarito existentes.
    3. As correções devem visar a melhoria da qualidade e da precisão do enunciado, sem modificar o problema central 
    proposto ou o nível de dificuldade pretendido.
    4. No campo "correcoes_detalhadas" do JSON de saída, descreva objetivamente todas as alterações significativas 
    realizadas no enunciado e justifique brevemente por que foram necessárias (ex: "Correção de concordância verbal na 
    segunda frase para maior clareza.", "Ajuste na definição de X para precisão conceitual.", "Remoção de informação 
    redundante que não contribuía para a pergunta.").
    5. Se o enunciado original já estiver perfeito e não necessitar de correções, indique isso claramente no campo 
    "correcoes_detalhadas" (ex: "Nenhuma correção necessária. O enunciado original está gramaticalmente correto,
    conceitualmente preciso e claro.").
    6. Não esquecer de colocar a URL da fonte de onde o texto de apoio foi retirado.
  expected_output: >
    Um json sem ``` com as chaves "enunciado", "alternativas", "gabarito_original" e "correcoes" preenchidas com os valores correspondentes.
    Exemplo de saída:

      {
      "texto_apoio": "Durante o século XIX, a Revolução Industrial começou a substituir o trabalho artesanal e agrícola por processos de produção em fábricas. Pessoas que antes trabalhavam em pequenas propriedades rurais migraram em massa para centros urbanos em busca de emprego. Essa rápida urbanização fez com que bairros operários crescessem ao redor das indústrias, e as atividades diárias passaram a girar em torno do ritmo das máquinas e da disciplina fabril, ao invés dos ciclos sazonais do campo.",
      "Disponível em: http://thumbpress.com/. Acesso em: 28 out. 2013"
      "enunciado": "Considerando o contexto apresentado no texto de apoio, qual das seguintes alternativas representa uma consequência social significativa dessa transformação durante a Revolução Industrial?",
      "alternativas": {
        "A": "Reforço do trabalho em pequenas propriedades rurais, com retorno dos trabalhadores às vilas do interior.",
        "B": "Aumento da influência de monarquias agrárias que sustentavam sistemas feudais tradicionais.",
        "C": "Formação de uma nova classe operária urbana submetida a jornadas de trabalho extensas em fábricas.",
        "D": "Desenvolvimento de tecnologia de transportes que tornou obsoletos os navios a vapor."
      },
      "gabarito_original": "C"

      "correcao": "A correção realizada foi em ...."
    }
  agent: revisor_questao
