melhorar_pergunta:
  description: >
    Melhora a pergunta do usuário, tornando-a mais clara para obter melhores respostas de ferramentas de IA.
    Deve manter o significado original da pergunta, sem acrescentar pedidos adicionais, mas melhorar a clareza e a precisão.
    Input do usuário: {input_user}
  expected_output: >
    Um json sem ``, e com as chaves "pergunta_original", "pergunta_melhorada" preenchidas com os valores correspondentes.
    Exemplo de saída:
    {
      "pergunta_original": "eu quero uma questão de química pra entrar na unicamp sobre Funções estruturas e ligações em quimica organica",
      "pergunta_melhorada": "Crie uma questão de múltipla escolha no estilo do vestibular da Unicamp sobre funções orgânicas, estrutura molecular e tipos de ligações em compostos orgânicos. A questão deve ter nível de dificuldade médio e incluir alternativas plausíveis, com gabarito e explicação comentada."
    }

  agent: melhorador_perguntas



filtrar_topicos:
  description: >
    Identifique a disciplina, categoria e a subcategoria da questão alvo que o usuário está solicitando.
    Input do usuário: {input_user}
  expected_output: >
    Um json sem ```, com as chaves "disciplina", "categoria" e "subcategoria" preenchidas com os valores correspondentes.
    Exemplo de saída:
    {
      "pedido": "Quero questões de vestibular sobre cinemática para entrar na faculdade",
      "disciplina": "Física",
      "categoria": "Mecânica",
      "subcategoria": "Cinemática"
    }
  agent: identificador_topicos


buscar_dados_para_questao:
  description: |
    Com base no pedido do usuário e no tópico da questão identificada, realize uma busca na internet
    para encontrar textos que possam ser utilizados como texto-base em uma questão de vestibular.


     Dê preferência para:
    - Reportagens jornalísticas;
    - Trechos de artigos de divulgação científica;
    - Ensaios, crônicas, textos opinativos ou literários (em Humanas ou Linguagens);
    - Estudos de caso, experimentos ou situações-problema (em Exatas e Biológicas).

    Não escolha textos introdutórios ou que contenham explicações sobre o tópico, mas sim textos que 
    demandem interpretação e análise crítica.

    Busque somente por fontes em português.
    Utilize a ferramenta de pesquisa para buscar na internet.

    Exemplos:
    {
      "search_query": "revolução industrial na literatura"
    } 

    {
      "search_query": "química orgânica últimas novidades"
    } 

    Depois de extraia o conteúdo relevante de cada fonte encontrada, seguindo as instruções abaixo.
    **EXTRAÇÃO RAW**  
    - Use web.open para obter o HTML bruto.
    - Use web.find (ou equivalente) com `raw: true` para capturar **todos** os <p>…</p>.
    - **Copie e cole** cada parágrafo exatamente como está no HTML, incluindo acentos, quebras de linha e pontuação.
    - **Não** altere, resuma, parafraseie ou corrija o texto original.

    Depois disso, selecione um ou mais parágrafos exatos, com no mínimo 50 palavras, para ser o texto de apoio.
    
  steps:
    - tool: web.open
      args:
        url: "{{url}}"
    - tool: web.find
      args:
        ref_id: last
        pattern: "<p>.*?</p>"
      raw: true

  expected_output: >
    Um arquivo JSON sem ```, com a url do website escolhido, o texto completo extraído do site, o texto de apoio selecionado e uma explicação do porquê esse texto é adequado para a elaboração de uma questão vestibular.
    {
      "url": "https://site1.com/exemplo",
      "texto_na_integra": "Aqui vai os parágrafos completos, exatamente como no site, sem nenhuma alteração.",
      "texto_apoio": "Aqui vai o parágrafo selecionado para servir de base.",
      "explicacao": "Este parágrafo aborda X, o que permite criar uma questão sobre Y em Biologia (Genética)."
    }
  agent: pesquisa_e_extracao
    

geração_questao:
  description: >
    Gere uma questão inédita de múltipla escolha para vestibulares e ENEM, com base em um tópico, categoria e subcategoria fornecidos.
    A questão deve ser elaborada no estilo dos principais exames brasileiros (como ENEM), focando na avaliação de competências essenciais do ensino médio.

    Instruções Detalhadas:

    1. Estrutura da Questão:
      Enunciado: Deve ser autocontido, apresentando um desenvolvimento de raciocínio relevante para construir a questão conectando com o texto, seguida de uma pergunta principal clara e objetiva. O enunciado 
      deve ter entre 50 e 200 palavras.
      Texto de apoio: Deve ser um trecho pesquisado pelo agente anterior (que busca textos online) e servir como base
      informativa para a elaboração da questão. Inclua esse texto no campo "texto_apoio" do JSON de saída.
      Alternativas: Crie 4 (quatro) alternativas de resposta, rotuladas como A, B, C, D.
    2. Qualidade das Alternativas:
      Correta: Apenas UMA alternativa deve ser inequivocamente correta, com base nos conhecimentos esperados para o 
      nível.
      Distratores: As outras três alternativas (distratores) devem ser plausíveis e atraentes, mas tecnicamente 
      incorretas. Idealmente, os distratores devem explorar erros conceituais comuns, interpretações parciais, 
      raciocínios falhos ou aplicação incorreta de fórmulas/conceitos. Evite alternativas absurdas ou facilmente 
      descartáveis.
    3. Conteúdo e Competências:
      A questão deve ser rigorosamente precisa em termos conceituais e factuais para o tópico fornecido.
      Deve avaliar habilidades cognitivas além da simples memorização, como interpretação de texto/dados, análise 
      crítica, raciocínio lógico, argumentação, resolução de problemas e aplicação de conhecimentos em novos contextos.
      Utilize o texto de apoio pesquisado pelo agente anterior como fonte principal de contexto e informações relevantes.
    4. Formato e Estilo:
      Utilize linguagem clara, precisa e adequada ao público do ensino médio e pré-vestibular.
      Se a questão envolver fórmulas matemáticas, gráficos, tabelas ou equações químicas, utilize a notação LaTeX 
      para representá-las corretamente. 
      A questão deve ser original, evitando cópias diretas de questões existentes, mas pode se inspirar na complexidade,
       no formato e no estilo de questões de exames anteriores.
    5. Restrições:
      Não inclua a identificação da resposta correta (gabarito) no texto do enunciado ou das alternativas. O gabarito 
      será especificado em um campo separado no JSON de saída.
      Não utilize as tools disponíveis para esta tarefa. A geração deve ser baseada exclusivamente no seu conhecimento 
      e nas instruções fornecidas.
      A questão deve ser solucionável com base no conhecimento tipicamente adquirido durante o Ensino Médio.
    6. Não esquecer de colocar a URL da fonte de onde o texto de apoio foi retirado.
  expected_output: >
    Um arquivo JSON sem ```, contendo as chaves "texto_apoio", "url", "enunciado", "alternativas" e "gabarito".
    A chave "texto_apoio" deve conter o trecho pesquisado pelo agente anterior.
    A chave "alternativas" deve ser um objeto com as chaves "A", "B", "C", "D", contendo os textos de cada alternativa.
    A chave "gabarito" deve conter a letra da alternativa correta.

    Exemplo de Saída:
    {
      "texto_apoio": "Durante o século XIX, a Revolução Industrial começou a substituir o trabalho artesanal e agrícola por processos de produção em fábricas. Pessoas que antes trabalhavam em pequenas propriedades rurais migraram em massa para centros urbanos em busca de emprego. Essa rápida urbanização fez com que bairros operários crescessem ao redor das indústrias, e as atividades diárias passaram a girar em torno do ritmo das máquinas e da disciplina fabril, ao invés dos ciclos sazonais do campo.",
      "url": "https://site1.com/exemplo",
      "enunciado": "Considerando o contexto apresentado no texto de apoio, qual das seguintes alternativas representa uma consequência social significativa dessa transformação durante a Revolução Industrial?",
      "alternativas": {
        "A": "Reforço do trabalho em pequenas propriedades rurais, com retorno dos trabalhadores às vilas do interior.",
        "B": "Aumento da influência de monarquias agrárias que sustentavam sistemas feudais tradicionais.",
        "C": "Formação de uma nova classe operária urbana submetida a jornadas de trabalho extensas em fábricas.",
        "D": "Desenvolvimento de tecnologia de transportes que tornou obsoletos os navios a vapor."
      },
      "gabarito": "C"
    }
  agent: redator_questao



resolucao_questao:
  description: >
    Solucione a questão de vestibular gerada previamente e explique o raciocínio por trás da resolução.
    Desenvolva a lógica de raciocínio e o embasamento teórico que fundamenta a resposta correta.
    Destaque a resposta final e alternativa correta entre as opções apresentadas. Se não houver uma alternativa correta, indique que a questão não possui uma resposta correta.
  expected_output: >
    Um json sem ```, com as chaves "Explicação", "Resposta final" e "Alternativa correta" preenchidas com os valores correspondentes.
    Exemplo de saída:
    {
      "Explicação": "A velocidade média é dada pela fórmula V = d/t, onde d é a distância e t é o tempo. Neste caso, d = 100 km e t = 2 h. Portanto, V = 100 km / 2 h = 50 km/h.",
      "Resposta final": "50 km/h",
      "Alternativa correta": "A"
    }
  agent: resolutor_questao

correção_questao:
  description: >
    Analise criticamente e corrija exclusivamente o enunciado de uma questão de vestibular previamente gerada.
    Input: Você receberá uma questão completa (com "enunciado" original, "alternativas" e "gabarito").
    Sua Tarefa:

    1. Identifique e corrija erros de gramática (ortografia, concordância, regência, pontuação), imprecisões na 
    fundamentação teórica, ambiguidades, falta de clareza ou informações redundantes/ausentes no enunciado.
    2.  NÃO altere as "alternativas" nem o "gabarito" fornecidos. Seu trabalho é ajustar o enunciado para que ele 
    esteja correto, claro e totalmente alinhado com as alternativas e o gabarito existentes.
    3. As correções devem visar a melhoria da qualidade e da precisão do enunciado, sem modificar o problema central 
    proposto ou o nível de dificuldade pretendido.
    4. No campo "correcoes_detalhadas" do JSON de saída, descreva objetivamente todas as alterações significativas 
    realizadas no enunciado e justifique brevemente por que foram necessárias (ex: "Correção de concordância verbal na 
    segunda frase para maior clareza.", "Ajuste na definição de X para precisão conceitual.", "Remoção de informação 
    redundante que não contribuía para a pergunta.").
    5. Se o enunciado original já estiver perfeito e não necessitar de correções, indique isso claramente no campo 
    "correcoes_detalhadas" (ex: "Nenhuma correção necessária. O enunciado original está gramaticalmente correto, 
    conceitualmente preciso e claro.").
    6. Não esquecer de colocar a URL da fonte de onde o texto de apoio foi retirado.

  expected_output: >
    Um json sem ```, com as chaves "texto_apoio", "url", "enunciado", "alternativas", "gabarito" e "correcao" preenchidas com os valores correspondentes.
    Exemplo de saída:

      {
      "texto_apoio": "Durante o século XIX, a Revolução Industrial começou a substituir o trabalho artesanal e agrícola por processos de produção em fábricas. Pessoas que antes trabalhavam em pequenas propriedades rurais migraram em massa para centros urbanos em busca de emprego. Essa rápida urbanização fez com que bairros operários crescessem ao redor das indústrias, e as atividades diárias passaram a girar em torno do ritmo das máquinas e da disciplina fabril, ao invés dos ciclos sazonais do campo.",
      "url": "https://site1.com/exemplo",
      "enunciado": "Considerando o contexto apresentado no texto de apoio, qual das seguintes alternativas representa uma consequência social significativa dessa transformação durante a Revolução Industrial?",
      "alternativas": {
        "A": "Reforço do trabalho em pequenas propriedades rurais, com retorno dos trabalhadores às vilas do interior.",
        "B": "Aumento da influência de monarquias agrárias que sustentavam sistemas feudais tradicionais.",
        "C": "Formação de uma nova classe operária urbana submetida a jornadas de trabalho extensas em fábricas.",
        "D": "Desenvolvimento de tecnologia de transportes que tornou obsoletos os navios a vapor."
      },
      "gabarito": "C"

      "correcao": "A correção realizada foi em ...."
      }
  agent: revisor_questao